sudo: require

language: generic

services:
  - docker

before_install:
  - docker build -t nonameb3/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nonameb3/docker-react npm run test

deploy:
  provider: elasticbeantalk
  regis: "ap-southeast-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-093338563717"
  bucket_path: "docker-react"
  on:
  branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
