sudo: require

language: generic

services:
  - docker

before_install:
  - docker build -t nonameb3/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nonameb3/docker-react npm run test
